// Generated by CoffeeScript 1.8.0
$(function() {
  var discount, discountValues, storageDuration, updatePrice;
  discount = 5;
  discountValues = new Array();
  $(".shelf-price").each(function(index) {
    var current, i, temp, _results;
    current = parseFloat($(this).text().slice(0, -2)).toFixed(2);
    $(this).html(current + " €");
    discountValues[index] = new Array();
    discountValues[index][0] = current;
    temp = 0;
    i = 1;
    _results = [];
    while (i < 30) {
      if (i === 5) {
        discount = discount / 1.5;
      }
      temp = discountValues[index][i - 1] * (1 - discount / 100);
      discountValues[index][i] = temp.toFixed(2);
      _results.push(i++);
    }
    return _results;
  });
  updatePrice = function(duration) {
    $(".shelf-price").each(function(index) {
      var price;
      price = discountValues[index][duration - 1];
      $(this).html(price + " €");
      return $(this).attr("data-price", price);
    });
    return $(".shelf-duration").each(function(index) {
      return $(this).find("input").val(duration);
    });
  };
  if (!localStorage.duration) {
    storageDuration = 1;
  } else {
    storageDuration = localStorage.duration;
  }
  if (storageDuration > 1) {
    $(".amount").val(storageDuration + " Tage");
  } else {
    $(".amount").val(storageDuration + " Tag");
  }
  updatePrice(storageDuration);
  return $(".slider").each(function() {
    return $(this).slider({
      range: "max",
      width: 200,
      min: 1,
      max: 30,
      value: storageDuration,
      slide: function(event, ui) {
        if (ui.value === 1) {
          $(".amount").val(ui.value + " Tag");
        } else {
          $(".amount").val(ui.value + " Tage");
        }
        localStorage.setItem("duration", ui.value);
        updatePrice(ui.value);
        return $(".slider").each(function() {
          return $(this).slider("option", "value", ui.value);
        });
      }
    });
  });
});
