// Generated by CoffeeScript 1.7.1
(function() {
  $(function() {
    var discount, discountValues, values;
    discount = 5;
    values = new Array();
    discountValues = new Array();
    $(".price").each(function(index) {
      var current, i, temp;
      current = parseFloat($(this).text().slice(0, -2)).toFixed(2);
      $(this).html(current + " €");
      discountValues[index] = new Array();
      discountValues[index][0] = current;
      temp = 0;
      i = 1;
      while (i < 30) {
        if (i === 5) {
          discount = discount / 1.5;
        }
        temp = discountValues[index][i - 1] * (1 - discount / 100);
        discountValues[index][i] = temp.toFixed(2);
        i++;
      }
    });
    $("#slider-range-max").slider({
      range: "max",
      min: 1,
      max: 30,
      value: 1,
      slide: function(event, ui) {
        if (ui.value === 1) {
          $("#amount").val(ui.value + " Tag");
        } else {
          $("#amount").val(ui.value + " Tage");
        }
        $(".price").each(function(index) {
          $(this).html(discountValues[index][ui.value - 1] + " €");
        });
      }
    });
    $("#amount").val($("#slider-range-max").slider("value") + " Tag");
  });

}).call(this);
