// Generated by CoffeeScript 1.8.0
var addCat, removeCat;

$(function() {
  return $("#cat-add").click(function() {
    addCat();
  });
});

removeCat = function(event) {
  var id;
  if (confirm("Kategorie wirklich löschen?")) {
    id = event.target.nextSibling.innerText;
  }
  return $.ajax({
    type: "post",
    url: "aux/articles/sql-remove-cat.php",
    data: "id=" + id,
    success: function() {
      root.growl("Kategorie erfolgreich gelöscht.", "success");
      return root.getList();
    }
  });
};

addCat = function(event) {
  var name;
  name = $("#new-cat-name").val();
  if (name === "" || name === void 0) {
    return root.growl("Bitte einen Namen hinzufügen.", "info");
  } else {
    return $.ajax({
      type: "post",
      url: "aux/articles/sql-add-cat.php",
      data: "name=" + name,
      success: function() {
        root.growl("Kategorie erfolgreich erstellt.", "success");
        return $("#cat-add-form").trigger("reset");
      }
    });
  }
};
