// Generated by CoffeeScript 1.8.0
var addCat, articleItem, assignCats, catItem, catsInit, root, selectedArticles, selectedCats, sqlGetArticles, sqlGetCats, sql_query, updateCatsOnArticleClick;

root = typeof exports !== "undefined" && exports !== null ? exports : this;

selectedArticles = [];

selectedCats = [];

$(function() {
  $("#cat-add").click(function() {
    return addCat();
  });
  $("#cat-assign").click(function() {
    if (selectedArticles.length !== 0 && selectedCats.length !== 0) {
      return assignCats();
    }
  });
  $("#selectableArticles").selectable({
    stop: function() {
      updateCatsOnArticleClick();
      selectedArticles = [];
      $(".ui-selected", this).each(function() {
        return selectedArticles.push($(this).attr("data-id"));
      });
      if (selectedArticles.length === 1) {
        return console.log("one");
      } else {
        return console.log("more");
      }
    }
  });
  return $("#selectableCats").selectable({
    stop: function() {
      selectedCats = [];
      return $(".ui-selected", this).each(function() {
        return selectedCats.push($(this).attr("data-id"));
      });
    }
  });
});

catsInit = function() {
  sqlGetArticles();
  return sqlGetCats();
};

root.removeCat = function(event) {
  return alert("Foo");
};

addCat = function(event) {
  var name;
  name = $("#new-cat-name").val();
  if (name === "" || name === void 0) {
    return root.growl("Bitte einen Namen hinzufügen.", "info");
  } else {
    return $.ajax({
      type: "post",
      url: "aux/articles/sql-add-cat.php",
      data: "name=" + name,
      success: function() {
        root.growl("Kategorie erfolgreich erstellt.", "success");
        $("#cat-add-form").trigger("reset");
        return sqlGetCats();
      }
    });
  }
};

assignCats = function() {
  var article, callback, cat, count, query, toggleInfo, _i, _j, _len, _len1, _results;
  toggleInfo = "#assign-info";
  $(toggleInfo).html("<span class='btn'><span class='glyphicon glyphicon-refresh'></span> Speichere...</span>");
  query = "INSERT INTO `Article_Category_Rel` (Article, Category) VALUES ";
  count = 0;
  _results = [];
  for (_i = 0, _len = selectedArticles.length; _i < _len; _i++) {
    article = selectedArticles[_i];
    for (_j = 0, _len1 = selectedCats.length; _j < _len1; _j++) {
      cat = selectedCats[_j];
      query += "(" + article + "," + cat + "),";
    }
    sql_query("DELETE FROM `Article_Category_Rel` WHERE Article = " + article, toggleInfo, false);
    count++;
    if (count === selectedArticles.length) {
      query = query.slice(0, -1) + ";";
      callback = function() {
        return sql_query(query, toggleInfo, true);
      };
      _results.push(setTimeout(callback, 500));
    } else {
      _results.push(void 0);
    }
  }
  return _results;
};

sql_query = function(query, toggleInfo, toggle) {
  return $.ajax({
    type: "post",
    url: "aux/articles/sql-query.php",
    data: "query=" + query,
    success: function() {
      if (toggle) {
        root.growl("Zuordnung erfolgreich erstellt.", "success");
        return $(toggleInfo).html("");
      }
    },
    error: function() {
      root.growl("Es ist etwas schief gegangen...", "info");
      return $(toggleInfo).html("");
    }
  });
};

updateCatsOnArticleClick = function() {
  return $("#selectableCats li").each(function() {
    $(this).removeClass("ui-selected");
    return selectedCats = [];
  });
};

sqlGetArticles = function() {
  return $.ajax({
    url: "aux/articles/sql-get-all-articles.php",
    type: "POST",
    data: "",
    dataType: "json",
    success: function(response) {
      return articleItem(response);
    }
  });
};

articleItem = function(data) {
  var article, content, _i, _len, _results;
  $("#selectableArticles li").remove();
  _results = [];
  for (_i = 0, _len = data.length; _i < _len; _i++) {
    article = data[_i];
    content = "<li class='' data-id='" + article.id + "'>" + article.Name + "</li>";
    _results.push($("#selectableArticles").append(content));
  }
  return _results;
};

sqlGetCats = function() {
  return $.ajax({
    url: "aux/articles/sql-get-all-cats.php",
    type: "POST",
    data: "",
    dataType: "json",
    success: function(response) {
      return catItem(response);
    },
    error: function() {}
  });
};

catItem = function(data) {
  var cat, content, _i, _len, _results;
  $("#selectableCats li").remove();
  _results = [];
  for (_i = 0, _len = data.length; _i < _len; _i++) {
    cat = data[_i];
    content = "<li class='' data-id='" + cat.id + "'>" + cat.Name + " <a class='remove' onclick='alert(event);' style='float: right;'><i class='fa fa-minus-circle fa-lg'></i></a></li>";
    _results.push($("#selectableCats").append(content));
  }
  return _results;
};
