// Generated by CoffeeScript 1.8.0
var addCat, articleItem, catItem, catsInit, removeCat, root, sqlGetArticles, sqlGetCats;

root = typeof exports !== "undefined" && exports !== null ? exports : this;

$(function() {
  return $("#cat-add").click(function() {
    addCat();
  });
});

catsInit = function() {
  sqlGetArticles();
  return sqlGetCats();
};

removeCat = function(event) {
  var id;
  if (confirm("Kategorie wirklich löschen?")) {
    id = event.target.nextSibling.innerText;
  }
  return $.ajax({
    type: "post",
    url: "aux/articles/sql-remove-cat.php",
    data: "id=" + id,
    success: function() {
      root.growl("Kategorie erfolgreich gelöscht.", "success");
      return root.getList();
    }
  });
};

addCat = function(event) {
  var name;
  name = $("#new-cat-name").val();
  if (name === "" || name === void 0) {
    return root.growl("Bitte einen Namen hinzufügen.", "info");
  } else {
    return $.ajax({
      type: "post",
      url: "aux/articles/sql-add-cat.php",
      data: "name=" + name,
      success: function() {
        root.growl("Kategorie erfolgreich erstellt.", "success");
        return $("#cat-add-form").trigger("reset");
      }
    });
  }
};

$(function() {
  $("#selectableArticles").selectable({
    stop: function() {
      var result;
      result = $("#select-result").empty();
      $(".ui-selected", this).each(function() {
        var index;
        index = $("#selectableArticles li").index(this);
        result.append(" #" + (index + 1));
      });
    }
  });
  $("#selectableCats").selectable({
    stop: function() {
      var result;
      result = $("#select-result-cats").empty();
      $(".ui-selected", this).each(function() {
        var index;
        index = $("#selectableCats li").index(this);
        result.append(" #" + (index + 1));
      });
    }
  });
  return;
});

sqlGetArticles = function() {
  return $.ajax({
    url: "aux/articles/sql-get-all-articles.php",
    type: "POST",
    data: "",
    dataType: "json",
    success: function(response) {
      articleItem(response);
    }
  });
};

articleItem = function(data) {
  var article, content, _i, _len;
  $("#selectableArticles li").remove();
  for (_i = 0, _len = data.length; _i < _len; _i++) {
    article = data[_i];
    content = "<li class='' data-id='" + article.id + "'>" + article.Name + "</li>";
    $("#selectableArticles").append(content);
  }
};

sqlGetCats = function() {
  return $.ajax({
    url: "aux/articles/sql-get-all-cats.php",
    type: "POST",
    data: "",
    dataType: "json",
    success: function(response) {
      return catItem(response);
    },
    error: function() {}
  });
};

catItem = function(data) {
  var cat, content, _i, _len;
  $("#selectableCats li").remove();
  for (_i = 0, _len = data.length; _i < _len; _i++) {
    cat = data[_i];
    content = "<li class='' data-id='" + cat.id + "'>" + cat.Name + "</li>";
    $("#selectableCats").append(content);
  }
};
