// Generated by CoffeeScript 1.8.0
var sqlGetArticlesEquip;

sqlGetArticlesEquip = function() {
  return $.ajax({
    url: "aux/articles/sql-get-all-articles.php",
    type: "POST",
    data: "",
    dataType: "json",
    success: function(response) {
      return articleList(response);
    }
  });
};
