// Generated by CoffeeScript 1.7.1
(function() {
  var root, updateForm;

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  root.selected = -1;

  updateForm = function(data) {
    var photo;
    photo = data.PhotoURL;
    $('#id-edit').val(data.id);
    $('#name-edit').val(data.Name);
    $('#description-edit').val(data.Description);
    $('#transmission-edit').val(data.Transmission);
    $('#category-edit').val(data.Category);
    $('#subcategory-edit').val(data.Subcategory);
    $('#photo-edit').val(photo);
    $('#weight-edit').val(data.Weight);
    $('#channel-edit').val(data.Channel);
    $('#price-edit').val(data.Price);
    $('#quantity-edit').val(data.Quantity);
    $('#created-edit').val(data.Created);
    $('#modified-edit').val(data.Modified);
    if (photo !== null && photo !== "" && photo !== void 0) {
      $("#show-photo-edit img").attr("src", "sites/funk/files/t-" + photo);
      return $("#show-photo-edit a").attr("href", "sites/funk/files/" + photo);
    }
  };

  $(function() {
    $("#tabs").tabs({
      show: {
        effect: "fade"
      }
    });
    $("#tabs").tabs("option", "disabled", [2]);
    $("#tabs").on("tabsactivate", function(event, ui) {
      var newIndex;
      newIndex = ui.newTab.index();
      if (newIndex === 2 && root.selected !== -1) {
        $.ajax({
          url: "aux/articles/sql-get.php",
          type: "POST",
          data: {
            id: root.selected
          },
          dataType: "json",
          success: function(response) {
            updateForm(response[0]);
          }
        });
      }
    });
  });

}).call(this);
