// Generated by CoffeeScript 1.7.1
(function() {
  var root;

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  root.selected = -1;

  $(function() {
    $("#tabs").tabs({
      show: {
        effect: "fade"
      }
    });
    return $("#tabs").on("tabsactivate", function(event, ui) {
      var newIndex;
      newIndex = ui.newTab.index();
      console.log("Switched to tab " + newIndex);
      if (newIndex === 2 && root.selected !== -1) {
        console.log("Selected: " + root.selected);
      }
    });
  });

  return;

}).call(this);
