// Generated by CoffeeScript 1.8.0
var createArticleList, root, updateForm;

root = typeof exports !== "undefined" && exports !== null ? exports : this;

root.selected = -1;

updateForm = function(data) {
  var photo;
  photo = data.PhotoURL;
  $('#id-edit').val(data.id);
  $('#name-edit').val(data.Name);
  $('#description-edit').val(data.Description);
  $('#transmission-edit').val(data.Transmission);
  $('#photo-edit').val(photo);
  $('#weight-edit').val(data.Weight);
  $('#channel-edit').val(data.Channel);
  $('#price-edit').val(data.Price);
  $('#quantity-edit').val(data.Quantity);
  $('#created-edit').val(data.Created);
  $('#modified-edit').val(data.Modified);
  if (data.is_equipment === "1" || data.is_equipment === 1) {
    $('input[name="is-equipment-edit"]').attr("checked", true);
  } else {
    $('input[name="is-equipment-edit"]').attr("checked", false);
  }
  if (photo !== null && photo !== "" && photo !== void 0) {
    $("#show-photo-edit img").attr("src", "sites/funk/files/t-" + photo);
    return $("#show-photo-edit a").attr("href", "sites/funk/files/" + photo);
  } else {
    $("#show-photo-edit img").attr("src", "");
    return $("#show-photo-edit a").attr("href", "");
  }
};

root.save_info = function(spanid) {
  return $(spanid).html("<span class='btn'><span class='glyphicon glyphicon-refresh'></span> Speichere...</span>");
};

root.save_info_clear = function(spanid) {
  return $(spanid).html("");
};

root.growl = function(message, type) {
  $.bootstrapGrowl(message, {
    ele: "body",
    type: type,
    offset: {
      from: "bottom",
      amount: 20
    },
    align: "center",
    width: "auto",
    delay: 4000,
    allow_dismiss: true,
    stackup_spacing: 10
  });
};

root.getList = function() {
  return $.ajax({
    url: "aux/articles/sql-get-all-articles.php",
    type: "POST",
    data: "",
    dataType: "json",
    success: function(response) {
      createArticleList(response);
    }
  });
};

createArticleList = function(data) {
  var article, photo, row, rowData, _i, _len;
  $("tbody#list tr").remove();
  for (_i = 0, _len = data.length; _i < _len; _i++) {
    article = data[_i];
    photo = article.PhotoURL;
    row = $("<tr class='row-header'>");
    if (photo !== "" &&  photo !== void 0 && photo !== null) {
      row.append("<td class='articlelist'><img class='articlelist' src='sites/funk/files/t-" + photo + "'></td>");
    } else {
      row.append("<td></td>");
    }
    row.append("<td><strong>" + article.Name + "</strong></td>");
    row.append("<td>" + article.Price + " €</td>");
    row.append("<td>" + article.Quantity + "</td>");
    row.append("<td> <a class='edit tips' data-toggle='tooltip' title='Diesen Artikel editieren' onclick='editSelectedArticle(event); return false;'><i class='fa fa-pencil fa-lg'></i><span style='display:none;'>" + article.id + "</span></a> <a class='remove tips' data-toggle='tooltip' title='Diesen Artikel unwiderruflich löschen' onclick='removeArticle(event);'><i class='fa fa-minus-circle fa-lg'></i><span style='display:none;'>" + article.id + "</span></a> </td>");
    rowData = $("<tr class='row-data'>");
    rowData.append("<td class='active'>&nbsp;</td><td class='active' colspan='4'>" + article.Description + "</td>");
    rowData.hide();
    $(".tips").tooltip();
    row.click(function() {
      return $(this).nextUntil("tr.row-header").slideToggle(0);
    });
    $("tbody#list").append(row);
    $("tbody#list").append(rowData);
  }
};

$(function() {
  $("#list > tr.row-header").click(function() {
    return console.log("foo");
  });
  $("#tabs").tabs({
    show: {
      effect: "fade"
    }
  });
  $("#tabs").tabs("option", "disabled", [2]);
  root.getList();
  $("#tabs").on("tabsactivate", function(event, ui) {
    var newIndex;
    newIndex = ui.newTab.index();
    if (newIndex === 2 && root.selected !== -1) {
      $.ajax({
        url: "aux/articles/sql-get.php",
        type: "POST",
        data: {
          id: root.selected
        },
        dataType: "json",
        success: function(response) {
          updateForm(response[0]);
        }
      });
    }
    if (newIndex === 0) {
      root.getList();
    }
    if (newIndex === 3) {
      root.catsInit();
    }
    if (newIndex === 4) {
      root.equipInit();
    }
  });
});
