// Generated by CoffeeScript 1.7.1
(function() {
  var makeAjaxRequest;

  makeAjaxRequest = function() {
    return $.ajax({
      url: "../../aux/articles/sql-get.php",
      type: "get",
      data: {
        id: root.selected
      },
      success: function(response) {
        console.log(response);
      }
    });
  };

  return;

}).call(this);
