// Generated by CoffeeScript 1.7.1
(function() {
  var root;

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  root.removeArticle = function(event) {
    var id;
    if (confirm("Artikel wirklich löschen?")) {
      id = event.target.nextSibling.innerText;
    }
    console.log(id);
    $.ajax({
      type: "post",
      url: "aux/articles/sql-remove.php",
      data: "id=" + id,
      success: function() {
        return root.growl("Artikel erfolgreich gelöscht.", "success");
      }
    });
  };

  root.editSelectedArticle = function(event) {
    root.selected = event.target.nextSibling.innerText;
    $("#tabs").tabs("enable");
    $("#tabs").tabs("option", "active", "2");
    return false;
  };

}).call(this);
